// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartInvoice.API.Data;
using SmartInvoice.API.Entities.JsonModels;

#nullable disable

namespace SmartInvoice.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314174223_AddConfigurationFields")]
    partial class AddConfigurationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartInvoice.API.Entities.AIProcessingLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AIRegion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AIService")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<decimal?>("EstimatedCostUSD")
                        .HasColumnType("decimal(10,4)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProcessingTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.HasIndex("FileId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("AIProcessingLogs");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<decimal>("AutoApproveThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BusinessLicense")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CurrentCycleStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ExtraInvoicesBalance")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAutoApproveEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalRepresentative")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaxInvoicesPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StorageQuotaGB")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubscriptionExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubscriptionPackageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedInvoicesThisMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CompanyId");

                    b.HasIndex("SubscriptionPackageId");

                    b.HasIndex("TaxCode")
                        .IsUnique();

                    b.ToTable("Companies", t =>
                        {
                            t.HasCheckConstraint("CHK_Companies_SubscriptionDates", "\"SubscriptionExpiredAt\" IS NULL OR \"SubscriptionExpiredAt\" > \"SubscriptionStartDate\"");
                        });
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FormTemplate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<ProcessingConfig>("ProcessingConfig")
                        .HasColumnType("jsonb");

                    b.Property<bool>("RequiresDigitalSignature")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresMCCQT")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresVAT")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresXML")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypeNameEN")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ValidationRuleConfig>("ValidationRules")
                        .HasColumnType("jsonb");

                    b.HasKey("DocumentTypeId");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.ExportConfig", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultCreditAccount")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DefaultDebitAccount")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DefaultTaxAccount")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DefaultWarehouse")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConfigId");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("ExportConfigs");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.ExportHistory", b =>
                {
                    b.Property<Guid>("ExportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExportFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExportedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FilterCriteria")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastDownloadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("S3Key")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer");

                    b.HasKey("ExportId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExportedBy");

                    b.ToTable("ExportHistories");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.FileStorage", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ArchivedToGlacier")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeletedFromS3")
                        .HasColumnType("boolean");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text");

                    b.Property<string>("S3BucketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("S3Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("S3VersionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("FileId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("S3Key")
                        .IsUnique();

                    b.HasIndex("UploadedBy");

                    b.ToTable("FileStorages");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<InvoiceExtractedData>("ExtractedData")
                        .HasColumnType("jsonb");

                    b.Property<string>("FormNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InvoiceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReplaced")
                        .HasColumnType("boolean");

                    b.Property<string>("MCCQT")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<float?>("OcrConfidenceScore")
                        .HasColumnType("real");

                    b.Property<Guid?>("OriginalFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProcessingMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<InvoiceRawData>("RawData")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ReplacedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAmountBeforeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TotalAmountInWords")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalTaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VisualFileId")
                        .HasColumnType("uuid");

                    b.HasKey("InvoiceId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("OriginalFileId");

                    b.HasIndex("ReplacedBy");

                    b.HasIndex("VisualFileId");

                    b.HasIndex("CompanyId", "CreatedAt");

                    b.HasIndex("CompanyId", "Status", "RiskLevel", "InvoiceDate");

                    b.ToTable("Invoices", t =>
                        {
                            t.HasCheckConstraint("CHK_Invoices_Amounts", "\"TotalAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.InvoiceAuditLog", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<List<AuditChange>>("Changes")
                        .HasColumnType("jsonb");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewData")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AuditId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("UserId");

                    b.ToTable("InvoiceAuditLogs");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.InvoiceCheckResult", b =>
                {
                    b.Property<Guid>("CheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CheckName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CheckOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CheckedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("jsonb");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Suggestion")
                        .HasColumnType("text");

                    b.HasKey("CheckId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceCheckResults");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.LocalBlacklistedCompany", b =>
                {
                    b.Property<Guid>("BlacklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("BlacklistId");

                    b.HasIndex("TaxCode")
                        .IsUnique();

                    b.ToTable("LocalBlacklist");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionText")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RelatedInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationId");

                    b.HasIndex("RelatedInvoiceId");

                    b.HasIndex("RelatedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("FailReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VnpBankCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VnpCardType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VnpPayDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VnpResponseCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VnpTransactionNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VnpTxnRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TransactionId");

                    b.HasIndex("PackageId");

                    b.HasIndex("VnpTxnRef")
                        .IsUnique();

                    b.HasIndex("CompanyId", "CreatedAt");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.SubscriptionPackage", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("HasAdvancedWorkflow")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAiProcessing")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAuditLog")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasErpIntegration")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRiskWarning")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxInvoicesPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PackageLevel")
                        .HasColumnType("integer");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerSixMonths")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerYear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StorageQuotaGB")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PackageId");

                    b.HasIndex("PackageCode")
                        .IsUnique();

                    b.ToTable("SubscriptionPackages");

                    b.HasData(
                        new
                        {
                            PackageId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trải nghiệm sức mạnh xử lý hóa đơn bằng AI dành cho cá nhân hoặc doanh nghiệp mới thành lập.",
                            HasAdvancedWorkflow = false,
                            HasAiProcessing = true,
                            HasAuditLog = false,
                            HasErpIntegration = false,
                            HasRiskWarning = false,
                            IsActive = true,
                            MaxInvoicesPerMonth = 30,
                            MaxUsers = 1,
                            PackageCode = "FREE",
                            PackageLevel = 1,
                            PackageName = "Gói Dùng Thử (Free)",
                            PricePerMonth = 0m,
                            PricePerSixMonths = 0m,
                            PricePerYear = 0m,
                            StorageQuotaGB = 1,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PackageId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giải pháp tối ưu cho doanh nghiệp siêu nhỏ, đáp ứng nhu cầu xử lý hóa đơn tự động cơ bản.",
                            HasAdvancedWorkflow = false,
                            HasAiProcessing = true,
                            HasAuditLog = false,
                            HasErpIntegration = false,
                            HasRiskWarning = false,
                            IsActive = true,
                            MaxInvoicesPerMonth = 200,
                            MaxUsers = 5,
                            PackageCode = "STARTER",
                            PackageLevel = 2,
                            PackageName = "Gói Khởi Nghiệp (Starter)",
                            PricePerMonth = 199000m,
                            PricePerSixMonths = 995000m,
                            PricePerYear = 1990000m,
                            StorageQuotaGB = 5,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PackageId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quản trị rủi ro toàn diện và tự động hóa quy trình phê duyệt cho doanh nghiệp vừa và nhỏ (SME).",
                            HasAdvancedWorkflow = true,
                            HasAiProcessing = true,
                            HasAuditLog = true,
                            HasErpIntegration = false,
                            HasRiskWarning = true,
                            IsActive = true,
                            MaxInvoicesPerMonth = 1000,
                            MaxUsers = 15,
                            PackageCode = "PRO",
                            PackageLevel = 3,
                            PackageName = "Gói Chuyên Nghiệp (Professional)",
                            PricePerMonth = 599000m,
                            PricePerSixMonths = 2995000m,
                            PricePerYear = 5990000m,
                            StorageQuotaGB = 20,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PackageId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giải pháp tùy biến chuyên sâu, tích hợp API trực tiếp vào hệ thống ERP của tập đoàn.",
                            HasAdvancedWorkflow = true,
                            HasAiProcessing = true,
                            HasAuditLog = true,
                            HasErpIntegration = true,
                            HasRiskWarning = true,
                            IsActive = true,
                            MaxInvoicesPerMonth = 99999,
                            MaxUsers = 999,
                            PackageCode = "ENTERPRISE",
                            PackageLevel = 4,
                            PackageName = "Gói Doanh Nghiệp (Enterprise)",
                            PricePerMonth = 1999000m,
                            PricePerSixMonths = 9995000m,
                            PricePerYear = 19990000m,
                            StorageQuotaGB = 100,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.SystemConfiguration", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConfigType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresRestart")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("ConfigId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CognitoSub")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastLoginUserAgent")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("jsonb");

                    b.Property<bool>("ReceiveEmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceiveInAppNotifications")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.AIProcessingLog", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.FileStorage", "FileStorage")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvoice.API.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.Navigation("FileStorage");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.Company", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.SubscriptionPackage", "SubscriptionPackage")
                        .WithMany()
                        .HasForeignKey("SubscriptionPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SubscriptionPackage");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.ExportConfig", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.Company", "Company")
                        .WithOne()
                        .HasForeignKey("SmartInvoice.API.Entities.ExportConfig", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.ExportHistory", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvoice.API.Entities.User", "Exporter")
                        .WithMany()
                        .HasForeignKey("ExportedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Exporter");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.FileStorage", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvoice.API.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.Invoice", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvoice.API.Entities.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvoice.API.Entities.FileStorage", "OriginalFile")
                        .WithMany()
                        .HasForeignKey("OriginalFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartInvoice.API.Entities.Invoice", "ReplacementInvoice")
                        .WithMany()
                        .HasForeignKey("ReplacedBy");

                    b.HasOne("SmartInvoice.API.Entities.FileStorage", "VisualFile")
                        .WithMany()
                        .HasForeignKey("VisualFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SmartInvoice.API.Entities.BuyerInfo", "Buyer", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .HasColumnType("text")
                                .HasColumnName("BuyerAddress");

                            b1.Property<string>("ContactPerson")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("BuyerContactPerson");

                            b1.Property<string>("Email")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("BuyerEmail");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("BuyerName");

                            b1.Property<string>("Phone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("BuyerPhone");

                            b1.Property<string>("TaxCode")
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("BuyerTaxCode");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsOne("SmartInvoice.API.Entities.InvoiceWorkflow", "Workflow", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ApprovedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ApprovedAt");

                            b1.Property<Guid?>("ApprovedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("ApprovedBy");

                            b1.Property<DateTime?>("RejectedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("RejectedAt");

                            b1.Property<Guid?>("RejectedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("RejectedBy");

                            b1.Property<string>("RejectionReason")
                                .HasColumnType("text")
                                .HasColumnName("RejectionReason");

                            b1.Property<DateTime?>("SubmittedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("SubmittedAt");

                            b1.Property<Guid?>("SubmittedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("SubmittedBy");

                            b1.Property<Guid>("UploadedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("UploadedBy");

                            b1.HasKey("InvoiceId");

                            b1.HasIndex("ApprovedBy");

                            b1.HasIndex("RejectedBy");

                            b1.HasIndex("SubmittedBy");

                            b1.HasIndex("UploadedBy");

                            b1.ToTable("Invoices");

                            b1.HasOne("SmartInvoice.API.Entities.User", "Approver")
                                .WithMany()
                                .HasForeignKey("ApprovedBy");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");

                            b1.HasOne("SmartInvoice.API.Entities.User", "Rejector")
                                .WithMany()
                                .HasForeignKey("RejectedBy");

                            b1.HasOne("SmartInvoice.API.Entities.User", "Submitter")
                                .WithMany()
                                .HasForeignKey("SubmittedBy");

                            b1.HasOne("SmartInvoice.API.Entities.User", "Uploader")
                                .WithMany()
                                .HasForeignKey("UploadedBy")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Approver");

                            b1.Navigation("Rejector");

                            b1.Navigation("Submitter");

                            b1.Navigation("Uploader");
                        });

                    b.OwnsOne("SmartInvoice.API.Entities.SellerInfo", "Seller", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .HasColumnType("text")
                                .HasColumnName("SellerAddress");

                            b1.Property<string>("BankAccount")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("SellerBankAccount");

                            b1.Property<string>("BankName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("SellerBankName");

                            b1.Property<string>("Email")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("SellerEmail");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("SellerName");

                            b1.Property<string>("Phone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("SellerPhone");

                            b1.Property<string>("TaxCode")
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("SellerTaxCode");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.Navigation("Buyer")
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DocumentType");

                    b.Navigation("OriginalFile");

                    b.Navigation("ReplacementInvoice");

                    b.Navigation("Seller")
                        .IsRequired();

                    b.Navigation("VisualFile");

                    b.Navigation("Workflow")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.InvoiceAuditLog", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.Invoice", "Invoice")
                        .WithMany("AuditLogs")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvoice.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.InvoiceCheckResult", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.Invoice", "Invoice")
                        .WithMany("CheckResults")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.Notification", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.Invoice", "RelatedInvoice")
                        .WithMany()
                        .HasForeignKey("RelatedInvoiceId");

                    b.HasOne("SmartInvoice.API.Entities.User", "RelatedUser")
                        .WithMany()
                        .HasForeignKey("RelatedUserId");

                    b.HasOne("SmartInvoice.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedInvoice");

                    b.Navigation("RelatedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvoice.API.Entities.SubscriptionPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.SystemConfiguration", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.User", b =>
                {
                    b.HasOne("SmartInvoice.API.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SmartInvoice.API.Entities.Invoice", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CheckResults");
                });
#pragma warning restore 612, 618
        }
    }
}
