name: Build and Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build_and_test:
    # LƯU Ý: Nếu bạn hết dung lượng GitHub Actions, hãy đổi 'ubuntu-latest' thành 'self-hosted'
    # sau khi đã cài đặt Runner trên máy cá nhân.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore SmartInvoiceShield.sln

    - name: Build Solution
      run: dotnet build SmartInvoiceShield.sln --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test SmartInvoice.Tests/SmartInvoice.Tests.csproj --configuration Release --no-build --verbosity normal
